import yay from '../img/icon/yay.png';
import jestLogo from '../img/icon/jestLogo.png';
import javaLogo from '../img/icon/javaLogo.svg';
import nodeJSLogo from '../img/icon/nodeJSLogo.png';
import reactLogo from '../img/icon/reactLogo.png';
import seleniumWebDriverLogo from '../img/icon/seleniumWebDriverLogo.png';
import jsLogo from '../img/icon/jsLogo.png';
import sceneBuilderLogo from '../img/icon/sceneBuilderLogo.png';
import appEngineLogo from '../img/icon/appEngineLogo.png';
import gitLogo from '../img/icon/gitLogo.png';
import antlrLogo from '../img/icon/antlrLogo.png';
import mySQLLogo2 from '../img/icon/mySQLLogo2.png';
import junitLogo from '../img/icon/junitLogo.png';
import github from '../img/icon/github.png';
import email from '../img/icon/email.png';
import linkedin from '../img/icon/linkedin.png';
import unity from '../img/icon/unity.png';
import csharp from '../img/icon/csharp.png';
import anaconda from '../img/icon/anaconda.png';
import jQuery from '../img/icon/jQuery.png';
import sass from '../img/icon/sass.png';
import pokeapi from '../img/icon/pokeapi.png';
import typescript from '../img/icon/typescript.png';

class Icons {
    static yay = { name: 'Yay', logo: yay, alt: 'Yay' };
    static jest = { name: 'Jest', logo: jestLogo, alt: "Jest testing framework" };
    static java = { name: 'Java', logo: javaLogo, alt: "Java"};
    static nodeJS = { name: 'NodeJS', logo: nodeJSLogo, alt: "NodeJS"};
    static reactJS = { name: 'ReactJS', logo: reactLogo, alt: "ReactJS"};
    static seleniumWebDriver = { name: 'Selenium WebDriver', logo: seleniumWebDriverLogo, alt: "Selenium WebDriver"};
    static javascript = { name: 'JavaScript', logo: jsLogo, alt: "JavaScript"};
    static sceneBuilder = { name: 'Scene Builder', logo: sceneBuilderLogo, alt: "Scene Builder"};
    static appEngine = { name: 'App Engine', logo: appEngineLogo, alt: "App Engine"};
    static git = { name: 'Git', logo: gitLogo, alt: "Git"};
    static antlr = { name: 'ANTLR', logo: antlrLogo, alt: "Antlr"};
    static mySQL = { name: 'MySQL', logo: mySQLLogo2, alt: "MySQL"};
    static junit = { name: 'JUnit', logo: junitLogo, alt: "JUnit"};
    static github = { name: 'GitHub', logo: github, alt: "GitHub"};
    static email = { name: 'Email', logo: email, alt: "Email"};
    static linkedin = { name: 'Linkedin', logo: linkedin, alt: "Linkedin"};
    static unity = { name: 'Unity', logo: unity, alt: "Unity"};
    static csharp = { name: 'CSharp', logo: csharp, alt: "CSharp"};
    static anaconda = { name: 'Anaconda', logo: anaconda, alt: "Anaconda"};
    static jQuery = { name: 'jQuery', logo: jQuery, alt: "jQuery"};
    static sass = { name: 'Sass', logo: sass, alt: "Sass"};
    static pokeapi = { name: 'PokeAPI', logo: pokeapi, alt: "PokeAPI"};
    static typescript = { name: 'TypeScript', logo: typescript, alt: "TypeScript"};
}

export default Icons;