import selectionSort from '../img/screenshot/selection-sort.png';
import skyvsseaLandingPage from '../img/screenshot/skyvssea-landing-page.png';
import skyvsseaCustomizationPage from '../img/screenshot/skyvssea-customization-page.png';
import pokedexGeneration from '../img/screenshot/pokedex-generation.png';
import pokedexGrid from '../img/screenshot/pokedex-grid.png';
import pokedexDetail from '../img/screenshot/pokedex-detail.png';
import pokedexDetailEvolution from '../img/screenshot/pokedex-detail-evolution.png';
import pokedexDetailList from '../img/screenshot/pokedex-detail-list.png';
import pokedexSearch from '../img/screenshot/pokedex-search.png';
import pokedexMbGeneration from '../img/screenshot/pokedex-mb-generation.png';
import pokedexMbGrid from '../img/screenshot/pokedex-mb-grid.png';
import pokedexMbDetail from '../img/screenshot/pokedex-mb-detail.png';
import pokedexMbDetail2 from '../img/screenshot/pokedex-mb-detail-2.png';
import pathalgo1 from '../img/screenshot/pathalgo1.png';
import pathalgo2 from '../img/screenshot/pathalgo2.png';
import pathalgo3 from '../img/screenshot/pathalgo3.png';
import pathalgo4 from '../img/screenshot/pathalgo4.png';
import shopee1 from '../img/screenshot/shopee1.png';
import shopee2 from '../img/screenshot/shopee2.png';
import shopee3 from '../img/screenshot/shopee3.png';
import shopee4 from '../img/screenshot/shopee4.png';
import shopee5 from '../img/screenshot/shopee5.png';
import shopee6 from '../img/screenshot/shopee6.png';
import shopee7 from '../img/screenshot/shopee7.png';
import shopee8 from '../img/screenshot/shopee8.png';

class Images {
    static selectionSort = { name: 'Selection Sort', src: selectionSort };
    static skyvsseaLandingPage = { name: 'Landing Page', src: skyvsseaLandingPage };
    static skyvsseaCustomizationPage = { name: 'Customization Page', src: skyvsseaCustomizationPage };
    static pokedexGeneration = { name: 'Pokedex Generation Page', src: pokedexGeneration };
    static pokedexGrid = { name: 'Pokedex Grid Page', src: pokedexGrid };
    static pokedexDetail = { name: 'Pokedex Detail Page', src: pokedexDetail };
    static pokedexDetailEvolution = { name: 'Pokedex Detail Page - Evolution', src: pokedexDetailEvolution };
    static pokedexDetailList = { name: 'Pokedex Detail Page - List', src: pokedexDetailList };
    static pokedexSearch = { name: 'Pokedex Grid Page - Search', src: pokedexSearch };
    static pokedexMbGeneration = { name: 'Pokedex Generation - Mobile', src: pokedexMbGeneration };
    static pokedexMbGrid = { name: 'Pokedex Grid - Mobile', src: pokedexMbGrid };
    static pokedexMbDetail = { name: 'Pokedex Detail - Mobile', src: pokedexMbDetail };
    static pokedexMbDetail2 = { name: 'Pokedex Detail 2 - Mobile', src: pokedexMbDetail2 };
    static pathalgo1 = { name: 'Pathalgo', src: pathalgo1 };
    static pathalgo2 = { name: 'Pathalgo', src: pathalgo2 };
    static pathalgo3 = { name: 'Pathalgo', src: pathalgo3 };
    static pathalgo4 = { name: 'Pathalgo', src: pathalgo4 };
    static shopee1 = { name: 'Shopee', src: shopee1 };
    static shopee2 = { name: 'Shopee', src: shopee2 };
    static shopee3 = { name: 'Shopee', src: shopee3 };
    static shopee4 = { name: 'Shopee', src: shopee4 };
    static shopee5 = { name: 'Shopee', src: shopee5 };
    static shopee6 = { name: 'Shopee', src: shopee6 };
    static shopee7 = { name: 'Shopee', src: shopee7 };
    static shopee8 = { name: 'Shopee', src: shopee8 };
}

export default Images;